//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetDemo.Webparts.TimeTrack {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class TimeTrack {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(TimeTrack target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control2() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "clienttemplates.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control3() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "clientforms.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control4() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "clientpeoplepicker.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control5() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "autofill.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control6() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "sp.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control7() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "sp.runtime.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control8() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "sp.core.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::TimesheetDemo.Webparts.TimeTrack.TimeTrack @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<!-- Required meta tags -->\r\n<meta charset=\"utf-8\" />\r\n<meta name=\"viewport" +
                        "\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n\r\n\r\n<!-- B" +
                        "ootstrap CSS -->\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"https://stackpath" +
                        ".bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\" integrity=\"sha384-9gVQ4" +
                        "dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4\" crossorigin=\"anonym" +
                        "ous\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdnjs.cloudflare.com" +
                        "/ajax/libs/tempusdominus-bootstrap-4/5.0.0/css/tempusdominus-bootstrap-4.min.css" +
                        "\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"https://netdna.bootstrapcdn.c" +
                        "om/font-awesome/4.7.0/css/font-awesome.css\" />\r\n\r\n<!-- Datatable CSS -->\r\n\r\n<lin" +
                        "k href=\"../../../_layouts/15/TimesheetDemo/Designs/toastr/toastr.css\" rel=\"style" +
                        "sheet\" />\r\n\r\n<!-- Custom CSS -->\r\n\r\n\r\n\r\n\r\n<link href=\"../../../_layouts/15/Times" +
                        "heetDemo/Designs/Kendo/kendo.common-bootstrap.min.css\" rel=\"stylesheet\" />\r\n<lin" +
                        "k href=\"../../../_layouts/15/TimesheetDemo/Designs/Kendo/kendo.bootstrap.min.css" +
                        "\" rel=\"stylesheet\" />\r\n\r\n<link rel=\"stylesheet\" href=\"../../../_layouts/15/Times" +
                        "heetDemo/Designs/css/main.css\" />\r\n<link rel=\"stylesheet\" href=\"../../../_layout" +
                        "s/15/TimesheetDemo/Designs/css/ovewrite.css\" />\r\n<link rel=\"stylesheet\" href=\".." +
                        "/../../_layouts/15/TimesheetDemo/Designs/css//responsive.css\" />\r\n\r\n\r\n<script ty" +
                        "pe=\"text/javascript\" src=\"../../../_layouts/15/TimesheetDemo/Scripts/jquery-1.9." +
                        "1.js\"></script>\r\n<title>Timesheet - Log Your Time</title>\r\n<meta name=\"WebPartPa" +
                        "geExpansion\" content=\"full\" />\r\n\r\n<!-- Header -->\r\n\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control3();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control4();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control5();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control6();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control7();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control8();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n\r\n\r\n<section class=\"wrapper\">\r\n\r\n    <div class=\"container-fluid\">\r\n     " +
                        "   <div class=\"row\">\r\n\r\n\r\n            <div class=\"col maincontainer p-3\">\r\n     " +
                        "           <div class=\"container\">\r\n\r\n                    <!-- The Modal -->\r\n\r\n" +
                        "                </div>\r\n                <div class=\"row\" id=\"buttons_AddEmployee" +
                        "\">\r\n                    <div class=\"col mb-3\">\r\n                        <div cla" +
                        "ss=\"p-2 ribbon-btn search-filter\">\r\n                            <button type=\"bu" +
                        "tton\" class=\"btn btn-success mr-3 add-button\" id=\"addemployee\"><i class=\"fa fa-p" +
                        "lus-circle\" aria-hidden=\"true\"></i>Add Time </button>\r\n                         " +
                        "   <button type=\"button\" style=\"display: none;\" class=\"btn btn-success mr-3 clos" +
                        "e-button close-client\" id=\"close-addemployee\"><i class=\"fa fa-close\" aria-hidden" +
                        "=\"true\"></i>Close</button>\r\n\r\n                        </div>\r\n\r\n                " +
                        "    </div>\r\n\r\n                </div>\r\n                <div id=\"form_AddEmployee\"" +
                        ">\r\n                    <div class=\"add-employee add-form p-3 mb-3\">\r\n           " +
                        "             <h6 class=\"mb-3 emp-details\">Submit Your Time:</h6>\r\n              " +
                        "          <div class=\"row\">\r\n                            <div class=\"col-md-4 mb" +
                        "-2\">\r\n                                <div class=\"form-group\">\r\n                " +
                        "                    <label for=\"First Name\">Title<em>*</em></label>\r\n           " +
                        "                         <input type=\"text\" class=\"form-control\" id=\"txtTitle\" p" +
                        "laceholder=\"Task Title\">\r\n                                </div>\r\n              " +
                        "              </div>\r\n                            <div class=\"col-md-4 mb-2\">\r\n " +
                        "                               <div class=\"form-group\">\r\n                       " +
                        "             <label for=\"First Name\">Description<em>*</em></label>\r\n            " +
                        "                        <textarea class=\"form-control\" id=\"txtDescription\" place" +
                        "holder=\"Task Description\"></textarea>\r\n                                </div>\r\n " +
                        "                           </div>\r\n                            <div class=\"col-m" +
                        "d-4 mb-2\">\r\n                                <div class=\"form-group\">\r\n          " +
                        "                          <label for=\"Country Code\">Category</label>\r\n          " +
                        "                          <select class=\"form-control\" id=\"drpCategory\" placehol" +
                        "der=\"\">\r\n                                        <option value=\"Select\">Select</" +
                        "option>\r\n                                        <option value=\"Billable\">Billin" +
                        "g</option>\r\n                                        <option value=\"Non-Billable\"" +
                        ">Non-Billable</option>\r\n                                        <option value=\"U" +
                        "pskilling\">Upskilling</option>\r\n                                        <option " +
                        "value=\"Meeting\">Meeting</option>\r\n                                    </select>\r" +
                        "\n                                </div>\r\n                            </div>\r\n   " +
                        "                     </div>\r\n\r\n                        <div class=\"row\">\r\n      " +
                        "                      <div class=\"col-md-4 mb-2\">\r\n                             " +
                        "   <div class=\"form-group\">\r\n                                    <label for=\"Mob" +
                        "ile Number\">Hours</label>\r\n                                    <input type=\"text" +
                        "\" class=\"form-control\" id=\"txtHours\" placeholder=\"Enter the hours\">\r\n           " +
                        "                     </div>\r\n                            </div>\r\n               " +
                        "             <div class=\"col-md-4 mb-2\">\r\n                                <div c" +
                        "lass=\"form-group\">\r\n                                    <label for=\"Email\">Hours" +
                        " (Allowed)</label>\r\n                                    <input type=\"text\" class" +
                        "=\"form-control\" id=\"txtHoursAllowed\" placeholder=\"\">\r\n                          " +
                        "      </div>\r\n                            </div>\r\n                            <d" +
                        "iv class=\"col-md-4 mb-2\">\r\n                                <div class=\"form-grou" +
                        "p\">\r\n                                    <label for=\"Email\">Hours (Overtime)</la" +
                        "bel>\r\n                                    <input type=\"text\" class=\"form-control" +
                        "\" id=\"txtHoursOvertime\" placeholder=\"\">\r\n                                </div>\r" +
                        "\n\r\n                            </div>\r\n                        </div>\r\n\r\n       " +
                        "                 <br />\r\n                        <br />\r\n\r\n                     " +
                        "   <div class=\"row\">\r\n                            <div class=\"col mb-2\">\r\n      " +
                        "                          <div class=\"form-group text-right\">\r\n                 " +
                        "                   <button type=\"button\" id=\"btnSave\" class=\"sm-btn btn-outline-" +
                        "primary  mr-3\" value=\"Save\">Save</button>\r\n                                    <" +
                        "button type=\"button\" id=\"btnCancel\" class=\"sm-btn btn-outline-primary\" value=\"Ca" +
                        "ncel\">Cancel</button>\r\n                                </div>\r\n                 " +
                        "           </div>\r\n                        </div>\r\n                    </div>\r\n\r" +
                        "\n                </div>\r\n\r\n                <!--Add Customer Ends-->\r\n           " +
                        "     <div class=\"row tab_Results\" id=\"tab_Employees\">\r\n                    <div " +
                        "class=\"col loaderContent1\">\r\n                        <ul class=\"nav nav-tabs\" id" +
                        "=\"employeetab\" role=\"tablist\">\r\n                            <li class=\"nav-item " +
                        "col pl-0 pr-0\">\r\n                                <a class=\"nav-link emp_ViewAll " +
                        "active\" id=\"tab-all-clients\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\" aria-c" +
                        "ontrols=\"profile\" aria-selected=\"false\">Timesheet Entries</a>\r\n                 " +
                        "           </li>\r\n\r\n                        </ul>\r\n                        <div " +
                        "class=\"preloader1\"><span class=\"preloader-content\" id=\"preloader-Clients\">Loadin" +
                        "g All Data...</span></div>\r\n                        <div class=\"tab-content p-3\"" +
                        " id=\"myTabContent\">\r\n                            <div class=\"tab-pane fade show " +
                        "active\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n                 " +
                        "               \r\n                                <div id=\"resultsGrid\"></div>\r\n " +
                        "                           </div>\r\n                        </div>\r\n             " +
                        "       </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    <" +
                        "/div>\r\n\r\n</section>\r\n\r\n\r\n<script type=\"text/javascript\" src=\"https://cdnjs.cloud" +
                        "flare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n<script type=" +
                        "\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/m" +
                        "oment.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"https://maxcdn.boot" +
                        "strapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n<script type=\"text/" +
                        "javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-" +
                        "4/5.0.0/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n<script type=\"text/javas" +
                        "cript\" src=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js\"" +
                        "></script>\r\n\r\n<!-- Datatable JS -->\r\n\r\n<script type=\"text/x-kendo-template\" id=\"" +
                        "selectTemplate_ViewMore\">\r\n    <a class=\"view-more item-viewmore\" onclick=\"openp" +
                        "opup(this)\"><i class=\"fa fa-external-link\" aria-hidden=\"true\"></i><span>View Mor" +
                        "e</span></a>\r\n</script>\r\n\r\n\r\n\r\n<script type=\"text/x-kendo-template\" id=\"selectTe" +
                        "mplate_InActive\">\r\n  \r\n         <div class=\"dropdown settings-icon\" data-id=\"#=d" +
                        "ata.id#\">                                                                       " +
                        "                                                                                " +
                        "          \r\n     <i data-toggle=\"dropdown\" aria-expanded=\"false\" class=\"fa fa-co" +
                        "gs\" aria-hidden=\"true\"></i>                                                     " +
                        "                                                  \r\n     <div class=\"dropdown-me" +
                        "nu dropdown-menu-right\">\r\n            <a class=\"dropdown-item item-edit d-flex a" +
                        "lign-items-center\" onclick=\'EditListItem(this)\'><span class=\"setting-dropdown\"><" +
                        "i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i></span><span>Edit</span><" +
                        "/a> \r\n            <a class=\"dropdown-item d-flex align-items-center\" onclick=\'Se" +
                        "ndInvitation(this)\'><span class=\"setting-dropdown\"><i class=\"fa fa-paper-plane-o" +
                        "\" aria-hidden=\"true\"></i></span><span>Send Invitation</span></a>     \r\n         " +
                        "   <a class=\"dropdown-item item-inactive d-flex align-items-center\" onclick=\'Upd" +
                        "ateItemToInActive(this)\'><span class=\"setting-dropdown\"><i class=\"fa fa-eye-slas" +
                        "h\" aria-hidden=\"true\"></i></span><span>Make Inactive</span></a>           \r\n    " +
                        "        <a class=\"dropdown-item item-delete d-flex align-items-center\" onclick=\'" +
                        "DeleteListItem(this)\'><span class=\"setting-dropdown\"><i class=\"fa fa-trash-o\" ar" +
                        "ia-hidden=\"true\"></i></span><span>Delete</span></a>                    \r\n       " +
                        "  \r\n                            \r\n     </div>                                   " +
                        "                                                                                " +
                        "                                                                        \r\n </div" +
                        ">\r\n</script>\r\n<script type=\"text/x-kendo-template\" id=\"selectTemplate_Active\">\r\n" +
                        "  \r\n         <div class=\"dropdown settings-icon\" data-id=\"#=data.id#\">          " +
                        "                                                                                " +
                        "                                                                       \r\n     <i" +
                        " data-toggle=\"dropdown\" aria-expanded=\"false\" class=\"fa fa-cogs\" aria-hidden=\"tr" +
                        "ue\"></i>                                                                        " +
                        "                               \r\n     <div class=\"dropdown-menu dropdown-menu-ri" +
                        "ght\">\r\n            <a class=\"dropdown-item item-edit d-flex align-items-center\" " +
                        "onclick=\'EditListItem(this)\'><span class=\"setting-dropdown\"><i class=\"fa fa-penc" +
                        "il-square-o\" aria-hidden=\"true\"></i></span><span>Edit</span></a> \r\n            <" +
                        "a class=\"dropdown-item d-flex align-items-center\" onclick=\'SendInvitation(this)\'" +
                        "><span class=\"setting-dropdown\"><i class=\"fa fa-paper-plane-o\" aria-hidden=\"true" +
                        "\"></i></span><span>Send Invitation</span></a>     \r\n            <a class=\"dropdo" +
                        "wn-item item-active d-flex align-items-center\" onclick=\'UpdateItemToActive(this)" +
                        "\'><span class=\"setting-dropdown\"><i class=\"fa fa-eye-slash\" aria-hidden=\"true\"><" +
                        "/i></span><span>Make Active</span></a>           \r\n            <a class=\"dropdow" +
                        "n-item item-delete d-flex align-items-center\" onclick=\'DeleteListItem(this)\'><sp" +
                        "an class=\"setting-dropdown\"><i class=\"fa fa-trash-o\" aria-hidden=\"true\"></i></sp" +
                        "an><span>Delete</span></a>                    \r\n         \r\n                     " +
                        "       \r\n     </div>                                                            " +
                        "                                                                                " +
                        "                                               \r\n </div>\r\n</script>\r\n\r\n<!-- Cust" +
                        "om JS -->\r\n<script type=\"text/javascript\" src=\"../../../_layouts/15/TimesheetDem" +
                        "o//Scripts/Controller/Control_Kendo.js\"></script>\r\n<script type=\"text/javascript" +
                        "\" src=\"../../../_layouts/15/TimesheetDemo/Designs/toastr/toastr.js\"></script>\r\n<" +
                        "script type=\"text/javascript\" src=\"../../../_layouts/15/TimesheetDemo//Scripts/m" +
                        "ain.js\"></script>\r\n<script type=\"text/javascript\" src=\"../../../_layouts/15/Time" +
                        "sheetDemo//Scripts/kendo/kendo.all.min.js\"></script>\r\n<script type=\"text/javascr" +
                        "ipt\" src=\"../../../_layouts/15/TimesheetDemo//Scripts/Controller/Control_Timeshe" +
                        "et.js\"></script>\r\n\r\n\r\n\r\n<script type=\"text/javascript\">\r\n    $(document).ready(f" +
                        "unction () {\r\n        onLoadSetup();\r\n        $(\'#addemployee\').click(function (" +
                        ") {\r\n            $(\'#tab_Employees\').hide();\r\n        });\r\n    });\r\n\r\n    functi" +
                        "on onLoadSetup() {\r\n        $(\'#sideNavBox\').hide();\r\n    }\r\n\r\n    function subm" +
                        "it() {\r\n        var timeInputs = {\r\n            \"title\": \"Web Input\",\r\n         " +
                        "   \"description\": \"Test Description\"\r\n        };\r\n        $.ajax({\r\n            " +
                        "type: \"POST\",\r\n            url: \"http://www.testservice.com/service1.svc/AddTime" +
                        "\",\r\n            data: JSON.stringify(timeInputs),\r\n            contentType: \"app" +
                        "lication/json;charset=utf-8\",\r\n            headers: { \"Allow-Control-Allow-Origi" +
                        "n\": \"*\" },\r\n            dataType: \"json\",\r\n            processData: true,\r\n     " +
                        "       success: function (data, status, jqXHR) {\r\n                toastr.success" +
                        "(\'Submitted successfully\');\r\n                alert(\'success \' + data);\r\n        " +
                        "    },\r\n            error: function (xhr) {\r\n                alert(xhr.responseT" +
                        "ext);\r\n            }\r\n        });\r\n    }\r\n\r\n    function showresult_CurrentAsset" +
                        "Location() {\r\n\r\n        var siteURL = _spPageContextInfo.siteAbsoluteUrl;\r\n     " +
                        "   $.ajax({\r\n            type: \"POST\",\r\n            url: siteURL + \"/_layouts/15" +
                        "/TimesheetService.aspx/GetTimeSheet\",\r\n            data: \'{userId:1}\',\r\n        " +
                        "    dataType: \"json\",\r\n            contentType: \"application/json; charset=utf-8" +
                        "\",\r\n            success: function (data) {\r\n                console.log(data)\r\n " +
                        "           },\r\n            error(jqXHR, textStatus, errorThrown) {\r\n            " +
                        "    console.log(errorThrown);\r\n            }\r\n        });\r\n\r\n    }\r\n\r\n</script>\r" +
                        "\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
