//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetDemo.Webparts.TimeTrack {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class TimeTrack {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(TimeTrack target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control2() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "clienttemplates.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control3() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "clientforms.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control4() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "clientpeoplepicker.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control5() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "autofill.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control6() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "sp.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control7() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "sp.runtime.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control8() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Name = "sp.core.js";
            @__ctrl.LoadAfterUI = true;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::TimesheetDemo.Webparts.TimeTrack.TimeTrack @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<!-- Required meta tags -->\r\n<meta charset=\"utf-8\" />\r\n<meta name=\"viewport" +
                        "\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n\r\n\r\n<!-- B" +
                        "ootstrap CSS -->\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"https://stackpath" +
                        ".bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\" integrity=\"sha384-9gVQ4" +
                        "dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4\" crossorigin=\"anonym" +
                        "ous\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdnjs.cloudflare.com" +
                        "/ajax/libs/tempusdominus-bootstrap-4/5.0.0/css/tempusdominus-bootstrap-4.min.css" +
                        "\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"https://netdna.bootstrapcdn.c" +
                        "om/font-awesome/4.7.0/css/font-awesome.css\" />\r\n\r\n<!-- Datatable CSS -->\r\n\r\n<lin" +
                        "k href=\"../../../_layouts/15/TimesheetDemo/Designs/toastr/toastr.css\" rel=\"style" +
                        "sheet\" />\r\n\r\n<!-- Custom CSS -->\r\n\r\n\r\n\r\n\r\n<link href=\"../../../_layouts/15/Times" +
                        "heetDemo/Designs/Kendo/kendo.common-bootstrap.min.css\" rel=\"stylesheet\" />\r\n<lin" +
                        "k href=\"../../../_layouts/15/TimesheetDemo/Designs/Kendo/kendo.bootstrap.min.css" +
                        "\" rel=\"stylesheet\" />\r\n\r\n<link rel=\"stylesheet\" href=\"../../../_layouts/15/Times" +
                        "heetDemo/Designs/css/main.css\" />\r\n<link rel=\"stylesheet\" href=\"../../../_layout" +
                        "s/15/TimesheetDemo/Designs/css/ovewrite.css\" />\r\n<link rel=\"stylesheet\" href=\".." +
                        "/../../_layouts/15/TimesheetDemo/Designs/css//responsive.css\" />\r\n\r\n\r\n<script ty" +
                        "pe=\"text/javascript\" src=\"../../../_layouts/15/TimesheetDemo/Scripts/jquery-1.9." +
                        "1.js\"></script>\r\n<title>Timesheet - Log Your Time</title>\r\n<meta name=\"WebPartPa" +
                        "geExpansion\" content=\"full\" />\r\n\r\n<!-- Header -->\r\n\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control3();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control4();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control5();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control6();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control7();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control8();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n\r\n\r\n<section class=\"wrapper\">\r\n\r\n    <div class=\"container-fluid\">\r\n     " +
                        "   <div class=\"row\">\r\n\r\n          \r\n            <div class=\"col maincontainer p-" +
                        "3\">\r\n                <div class=\"container\">\r\n\r\n                    <!-- The Mod" +
                        "al -->\r\n                    <div class=\"modal\" id=\"myModal\">\r\n                  " +
                        "      <div class=\"modal-dialog modal-sm modal-dialog-centered\">\r\n               " +
                        "             <div class=\"modal-content\">\r\n\r\n                                <!--" +
                        " Modal Header -->\r\n                                <div class=\"modal-header\">\r\n " +
                        "                                   <h6 class=\"modal-title\">Client Details</h6>\r\n" +
                        "                                    <button type=\"button\" class=\"close\" data-dis" +
                        "miss=\"modal\">&times;</button>\r\n                                </div>\r\n\r\n\r\n     " +
                        "                           <style>\r\n                                    .popacti" +
                        "on-save, .popaction-cancel {\r\n                                        display: n" +
                        "one;\r\n                                    }\r\n                                </s" +
                        "tyle>\r\n                                <!-- Modal body -->\r\n                    " +
                        "            <div class=\"modal-body\">\r\n                                    <div c" +
                        "lass=\"edit-section\">\r\n                                        <span class=\"edit-" +
                        "item popaction-edititem\"><i class=\"fa fa-edit popaction-edit\" aria-hidden=\"true\"" +
                        "></i>Edit</span>\r\n                                        <button type=\"button\" " +
                        "class=\"btn btn-success popaction-save\">Save</button>\r\n                          " +
                        "              <button type=\"button\" class=\"btn popaction-cancel\">Cancel</button>" +
                        "\r\n                                    </div>\r\n                                  " +
                        "  <div class=\"form-horizontal\">\r\n                                        <div cl" +
                        "ass=\"form-group row\">\r\n                                            <label class=" +
                        "\"control-label col-md-4\">Client Name <em>*</em></label>\r\n                       " +
                        "                     <div class=\"col-md-8\">\r\n                                   " +
                        "             <input type=\"text\" id=\"ptxtClientName\" class=\"form-control\" />\r\n   " +
                        "                                         </div>\r\n                               " +
                        "         </div>\r\n                                        <div class=\"form-group " +
                        "row\">\r\n                                            <label class=\"control-label c" +
                        "ol-md-4\">Client Location</label>\r\n                                            <d" +
                        "iv class=\"col-md-8\">\r\n                                                <input typ" +
                        "e=\"text\" id=\"ptxtClientLocation\" class=\"form-control\" />\r\n                      " +
                        "                      </div>\r\n                                        </div>\r\n  " +
                        "                                      <div class=\"form-group row\">\r\n            " +
                        "                                <label class=\"control-label col-md-4\">Country Co" +
                        "de</label>\r\n                                            <div class=\"col-md-8\">\r\n" +
                        "                                                <select class=\"form-control\" id=" +
                        "\"pdrpCountryCode\" placeholder=\"\">\r\n                                             " +
                        "       <option value=\"Select\">Select</option>\r\n                                 " +
                        "                   <option value=\"376\">AD - Andorra (+376)</option>\r\n           " +
                        "                                         <option value=\"971\">AE - United Arab Em" +
                        "irates (+971)</option>\r\n                                                    <opt" +
                        "ion value=\"93\">AF - Afghanistan (+93)</option>\r\n                                " +
                        "                    <option value=\"1268\">AG - Antigua And Barbuda (+1268)</optio" +
                        "n>\r\n                                                    <option value=\"1264\">AI " +
                        "- Anguilla (+1264)</option>\r\n                                                   " +
                        " <option value=\"355\">AL - Albania (+355)</option>\r\n                             " +
                        "                       <option value=\"374\">AM - Armenia (+374)</option>\r\n       " +
                        "                                             <option value=\"599\">AN - Netherland" +
                        "s Antilles (+599)</option>\r\n                                                    " +
                        "<option value=\"244\">AO - Angola (+244)</option>\r\n                               " +
                        "                     <option value=\"672\">AQ - Antarctica (+672)</option>\r\n      " +
                        "                                              <option value=\"54\">AR - Argentina " +
                        "(+54)</option>\r\n                                                    <option valu" +
                        "e=\"1684\">AS - American Samoa (+1684)</option>\r\n                                 " +
                        "                   <option value=\"43\">AT - Austria (+43)</option>\r\n             " +
                        "                                       <option value=\"61\">AU - Australia (+61)</" +
                        "option>\r\n                                                    <option value=\"297\"" +
                        ">AW - Aruba (+297)</option>\r\n                                                   " +
                        " <option value=\"994\">AZ - Azerbaijan (+994)</option>\r\n                          " +
                        "                          <option value=\"387\">BA - Bosnia And Herzegovina (+387)" +
                        "</option>\r\n                                                    <option value=\"12" +
                        "46\">BB - Barbados (+1246)</option>\r\n                                            " +
                        "        <option value=\"880\">BD - Bangladesh (+880)</option>\r\n                   " +
                        "                                 <option value=\"32\">BE - Belgium (+32)</option>\r" +
                        "\n                                                    <option value=\"226\">BF - Bu" +
                        "rkina Faso (+226)</option>\r\n                                                    " +
                        "<option value=\"359\">BG - Bulgaria (+359)</option>\r\n                             " +
                        "                       <option value=\"973\">BH - Bahrain (+973)</option>\r\n       " +
                        "                                             <option value=\"257\">BI - Burundi (+" +
                        "257)</option>\r\n                                                    <option value" +
                        "=\"229\">BJ - Benin (+229)</option>\r\n                                             " +
                        "       <option value=\"590\">BL - Saint Barthelemy (+590)</option>\r\n              " +
                        "                                      <option value=\"1441\">BM - Bermuda (+1441)<" +
                        "/option>\r\n                                                    <option value=\"673" +
                        "\">BN - Brunei Darussalam (+673)</option>\r\n                                      " +
                        "              <option value=\"591\">BO - Bolivia (+591)</option>\r\n                " +
                        "                                    <option value=\"55\">BR - Brazil (+55)</option" +
                        ">\r\n                                                    <option value=\"1242\">BS -" +
                        " Bahamas (+1242)</option>\r\n                                                    <" +
                        "option value=\"975\">BT - Bhutan (+975)</option>\r\n                                " +
                        "                    <option value=\"267\">BW - Botswana (+267)</option>\r\n         " +
                        "                                           <option value=\"375\">BY - Belarus (+37" +
                        "5)</option>\r\n                                                    <option value=\"" +
                        "501\">BZ - Belize (+501)</option>\r\n                                              " +
                        "      <option value=\"61\">CC - Cocos (keeling) Islands (+61)</option>\r\n          " +
                        "                                          <option value=\"243\">CD - Congo, The De" +
                        "mocratic Republic Of The (+243)</option>\r\n                                      " +
                        "              <option value=\"236\">CF - Central African Republic (+236)</option>\r" +
                        "\n                                                    <option value=\"242\">CG - Co" +
                        "ngo (+242)</option>\r\n                                                    <option" +
                        " value=\"41\">CH - Switzerland (+41)</option>\r\n                                   " +
                        "                 <option value=\"225\">CI - Cote D Ivoire (+225)</option>\r\n       " +
                        "                                             <option value=\"682\">CK - Cook Islan" +
                        "ds (+682)</option>\r\n                                                    <option " +
                        "value=\"56\">CL - Chile (+56)</option>\r\n                                          " +
                        "          <option value=\"237\">CM - Cameroon (+237)</option>\r\n                   " +
                        "                                 <option value=\"86\">CN - China (+86)</option>\r\n " +
                        "                                                   <option value=\"57\">CO - Colom" +
                        "bia (+57)</option>\r\n                                                    <option " +
                        "value=\"506\">CR - Costa Rica (+506)</option>\r\n                                   " +
                        "                 <option value=\"53\">CU - Cuba (+53)</option>\r\n                  " +
                        "                                  <option value=\"238\">CV - Cape Verde (+238)</op" +
                        "tion>\r\n                                                    <option value=\"61\">CX" +
                        " - Christmas Island (+61)</option>\r\n                                            " +
                        "        <option value=\"357\">CY - Cyprus (+357)</option>\r\n                       " +
                        "                             <option value=\"420\">CZ - Czech Republic (+420)</opt" +
                        "ion>\r\n                                                    <option value=\"49\">DE " +
                        "- Germany (+49)</option>\r\n                                                    <o" +
                        "ption value=\"253\">DJ - Djibouti (+253)</option>\r\n                               " +
                        "                     <option value=\"45\">DK - Denmark (+45)</option>\r\n           " +
                        "                                         <option value=\"1767\">DM - Dominica (+17" +
                        "67)</option>\r\n                                                    <option value=" +
                        "\"1809\">DO - Dominican Republic (+1809)</option>\r\n                               " +
                        "                     <option value=\"213\">DZ - Algeria (+213)</option>\r\n         " +
                        "                                           <option value=\"593\">EC - Ecuador (+59" +
                        "3)</option>\r\n                                                    <option value=\"" +
                        "372\">EE - Estonia (+372)</option>\r\n                                             " +
                        "       <option value=\"20\">EG - Egypt (+20)</option>\r\n                           " +
                        "                         <option value=\"291\">ER - Eritrea (+291)</option>\r\n     " +
                        "                                               <option value=\"34\">ES - Spain (+3" +
                        "4)</option>\r\n                                                    <option value=\"" +
                        "251\">ET - Ethiopia (+251)</option>\r\n                                            " +
                        "        <option value=\"358\">FI - Finland (+358)</option>\r\n                      " +
                        "                              <option value=\"679\">FJ - Fiji (+679)</option>\r\n   " +
                        "                                                 <option value=\"500\">FK - Falkla" +
                        "nd Islands (malvinas) (+500)</option>\r\n                                         " +
                        "           <option value=\"691\">FM - Micronesia, Federated States Of (+691)</opti" +
                        "on>\r\n                                                    <option value=\"298\">FO " +
                        "- Faroe Islands (+298)</option>\r\n                                               " +
                        "     <option value=\"33\">FR - France (+33)</option>\r\n                            " +
                        "                        <option value=\"241\">GA - Gabon (+241)</option>\r\n        " +
                        "                                            <option value=\"44\">GB - United Kingd" +
                        "om (+44)</option>\r\n                                                    <option v" +
                        "alue=\"1473\">GD - Grenada (+1473)</option>\r\n                                     " +
                        "               <option value=\"995\">GE - Georgia (+995)</option>\r\n               " +
                        "                                     <option value=\"233\">GH - Ghana (+233)</opti" +
                        "on>\r\n                                                    <option value=\"350\">GI " +
                        "- Gibraltar (+350)</option>\r\n                                                   " +
                        " <option value=\"299\">GL - Greenland (+299)</option>\r\n                           " +
                        "                         <option value=\"220\">GM - Gambia (+220)</option>\r\n      " +
                        "                                              <option value=\"224\">GN - Guinea (+" +
                        "224)</option>\r\n                                                    <option value" +
                        "=\"240\">GQ - Equatorial Guinea (+240)</option>\r\n                                 " +
                        "                   <option value=\"30\">GR - Greece (+30)</option>\r\n              " +
                        "                                      <option value=\"502\">GT - Guatemala (+502)<" +
                        "/option>\r\n                                                    <option value=\"167" +
                        "1\">GU - Guam (+1671)</option>\r\n                                                 " +
                        "   <option value=\"245\">GW - Guinea-bissau (+245)</option>\r\n                     " +
                        "                               <option value=\"592\">GY - Guyana (+592)</option>\r\n" +
                        "                                                    <option value=\"852\">HK - Hon" +
                        "g Kong (+852)</option>\r\n                                                    <opt" +
                        "ion value=\"504\">HN - Honduras (+504)</option>\r\n                                 " +
                        "                   <option value=\"385\">HR - Croatia (+385)</option>\r\n           " +
                        "                                         <option value=\"509\">HT - Haiti (+509)</" +
                        "option>\r\n                                                    <option value=\"36\">" +
                        "HU - Hungary (+36)</option>\r\n                                                   " +
                        " <option value=\"62\">ID - Indonesia (+62)</option>\r\n                             " +
                        "                       <option value=\"353\">IE - Ireland (+353)</option>\r\n       " +
                        "                                             <option value=\"972\">IL - Israel (+9" +
                        "72)</option>\r\n                                                    <option value=" +
                        "\"44\">IM - Isle Of Man (+44)</option>\r\n                                          " +
                        "          <option value=\"91\">IN - India (+91)</option>\r\n                        " +
                        "                            <option value=\"964\">IQ - Iraq (+964)</option>\r\n     " +
                        "                                               <option value=\"98\">IR - Iran, Isl" +
                        "amic Republic Of (+98)</option>\r\n                                               " +
                        "     <option value=\"354\">IS - Iceland (+354)</option>\r\n                         " +
                        "                           <option value=\"39\">IT - Italy (+39)</option>\r\n       " +
                        "                                             <option value=\"1876\">JM - Jamaica (" +
                        "+1876)</option>\r\n                                                    <option val" +
                        "ue=\"962\">JO - Jordan (+962)</option>\r\n                                          " +
                        "          <option value=\"81\">JP - Japan (+81)</option>\r\n                        " +
                        "                            <option value=\"254\">KE - Kenya (+254)</option>\r\n    " +
                        "                                                <option value=\"996\">KG - Kyrgyzs" +
                        "tan (+996)</option>\r\n                                                    <option" +
                        " value=\"855\">KH - Cambodia (+855)</option>\r\n                                    " +
                        "                <option value=\"686\">KI - Kiribati (+686)</option>\r\n             " +
                        "                                       <option value=\"269\">KM - Comoros (+269)</" +
                        "option>\r\n                                                    <option value=\"1869" +
                        "\">KN - Saint Kitts And Nevis (+1869)</option>\r\n                                 " +
                        "                   <option value=\"850\">KP - Korea Democratic Peoples Republic Of" +
                        " (+850)</option>\r\n                                                    <option va" +
                        "lue=\"82\">KR - Korea Republic Of (+82)</option>\r\n                                " +
                        "                    <option value=\"965\">KW - Kuwait (+965)</option>\r\n           " +
                        "                                         <option value=\"1345\">KY - Cayman Island" +
                        "s (+1345)</option>\r\n                                                    <option " +
                        "value=\"7\">KZ - Kazakstan (+7)</option>\r\n                                        " +
                        "            <option value=\"856\">LA - Lao Peoples Democratic Republic (+856)</opt" +
                        "ion>\r\n                                                    <option value=\"961\">LB" +
                        " - Lebanon (+961)</option>\r\n                                                    " +
                        "<option value=\"1758\">LC - Saint Lucia (+1758)</option>\r\n                        " +
                        "                            <option value=\"423\">LI - Liechtenstein (+423)</optio" +
                        "n>\r\n                                                    <option value=\"94\">LK - " +
                        "Sri Lanka (+94)</option>\r\n                                                    <o" +
                        "ption value=\"231\">LR - Liberia (+231)</option>\r\n                                " +
                        "                    <option value=\"266\">LS - Lesotho (+266)</option>\r\n          " +
                        "                                          <option value=\"370\">LT - Lithuania (+3" +
                        "70)</option>\r\n                                                    <option value=" +
                        "\"352\">LU - Luxembourg (+352)</option>\r\n                                         " +
                        "           \r\n                                                </select>\r\n        " +
                        "                                    </div>\r\n                                    " +
                        "    </div>\r\n                                        <div class=\"form-group row\">" +
                        "\r\n                                            <label class=\"control-label col-md" +
                        "-4\">Phone Number</label>\r\n                                            <div class" +
                        "=\"col-md-8\">\r\n                                                <input type=\"text\"" +
                        " id=\"ptxtMobileNumber\" class=\"form-control\" />\r\n                                " +
                        "            </div>\r\n                                        </div>\r\n            " +
                        "                            <div class=\"form-group row\">\r\n                      " +
                        "                      <label class=\"control-label col-md-4\">Email</label>\r\n     " +
                        "                                       <div class=\"col-md-8\">\r\n                 " +
                        "                               <input type=\"text\" id=\"ptxtEmail\" class=\"form-con" +
                        "trol\" />\r\n                                            </div>\r\n                  " +
                        "                      </div>\r\n                                        <div class" +
                        "=\"form-group row\">\r\n                                            <label class=\"co" +
                        "ntrol-label col-md-4\">VAT/CUI <em>*</em></label>\r\n                              " +
                        "              <div class=\"col-md-8\">\r\n                                          " +
                        "      <input type=\"text\" id=\"ptxtVAT\" class=\"form-control\" />\r\n                 " +
                        "                           </div>\r\n                                        </div" +
                        ">\r\n                                        <div class=\"form-group row\">\r\n       " +
                        "                                     <label class=\"control-label col-md-4\">Regis" +
                        "tration Number <em>*</em></label>\r\n                                            <" +
                        "div class=\"col-md-8\">\r\n                                                <input ty" +
                        "pe=\"text\" id=\"ptxtRegisterNumber\" class=\"form-control\" />\r\n                     " +
                        "                       </div>\r\n                                        </div>\r\n " +
                        "                                       \r\n                                       " +
                        " \r\n                                    </div>\r\n                                <" +
                        "/div>\r\n                            </div>\r\n                        </div>\r\n     " +
                        "               </div>\r\n                </div>\r\n                <div class=\"row\" " +
                        "id=\"buttons_AddEmployee\">\r\n                    <div class=\"col mb-3\">\r\n         " +
                        "               <div class=\"p-2 ribbon-btn search-filter\">\r\n                     " +
                        "       <button type=\"button\" class=\"btn btn-success mr-3 add-button\" id=\"addempl" +
                        "oyee\"><i class=\"fa fa-plus-circle\" aria-hidden=\"true\"></i>Add Client </button>\r\n" +
                        "                            <button type=\"button\" style=\"display: none;\" class=\"" +
                        "btn btn-success mr-3 close-button close-client\" id=\"close-addemployee\"><i class=" +
                        "\"fa fa-close\" aria-hidden=\"true\"></i>Close</button>\r\n\r\n                         " +
                        "   \r\n                            <div class=\"quicksearch right\">\r\n              " +
                        "                  <label for=\"input\" class=\"inf\">Quick Search:</label>\r\n        " +
                        "                        <input id=\"input\" class=\"form-control\" />\r\n             " +
                        "                   <button type=\"button\" id=\"clear\" class=\"btn btn-primary mr-3\"" +
                        " value=\"Cancel\">Clear Filter</button>\r\n                            </div>\r\n     " +
                        "                   </div>\r\n\r\n                    </div>\r\n\r\n                </div" +
                        ">\r\n                <div id=\"form_AddEmployee\">\r\n                    <div class=\"" +
                        "add-employee add-form p-3 mb-3\">\r\n                        <h6 class=\"mb-3 emp-de" +
                        "tails\">Client Details :</h6>\r\n                        <div class=\"row\">\r\n\r\n     " +
                        "                       <div class=\"col-md-4 mb-2\">\r\n                            " +
                        "    <div class=\"form-group\">\r\n                                    <label for=\"Fi" +
                        "rst Name\">Client Name <em>*</em></label>\r\n                                    <i" +
                        "nput type=\"text\" class=\"form-control\" id=\"txtClientName\" placeholder=\"\">\r\n      " +
                        "                          </div>\r\n                            </div>\r\n          " +
                        "                  <div class=\"col-md-4 mb-2\">\r\n                                <" +
                        "div class=\"form-group\">\r\n                                    <label for=\"First N" +
                        "ame\">Client Location</label>\r\n                                    <input type=\"t" +
                        "ext\" class=\"form-control\" id=\"txtClientLocation\" placeholder=\"\">\r\n              " +
                        "                  </div>\r\n                            </div>\r\n                  " +
                        "          <div class=\"col-md-4 mb-2\">\r\n                                <div clas" +
                        "s=\"form-group\">\r\n                                    <label for=\"Country Code\">C" +
                        "ountry Code</label>\r\n                                    <select class=\"form-con" +
                        "trol\" id=\"drpCountryCode\" placeholder=\"\">\r\n                                     " +
                        "   <option value=\"Select\">Select</option>\r\n                                     " +
                        "   <option value=\"376\">AD - Andorra (+376)</option>\r\n                           " +
                        "             <option value=\"971\">AE - United Arab Emirates (+971)</option>\r\n    " +
                        "                                    <option value=\"93\">AF - Afghanistan (+93)</o" +
                        "ption>\r\n                                        <option value=\"1268\">AG - Antigu" +
                        "a And Barbuda (+1268)</option>\r\n                                        <option " +
                        "value=\"1264\">AI - Anguilla (+1264)</option>\r\n                                   " +
                        "     <option value=\"355\">AL - Albania (+355)</option>\r\n                         " +
                        "           </select>\r\n                                </div>\r\n                  " +
                        "          </div>\r\n\r\n                        </div>\r\n\r\n                        <d" +
                        "iv class=\"row\">\r\n\r\n                            <div class=\"col-md-4 mb-2\">\r\n    " +
                        "                            <div class=\"form-group\">\r\n                          " +
                        "          <label for=\"Mobile Number\">Phone Number </label>\r\n                    " +
                        "                <input type=\"text\" class=\"form-control\" id=\"txtMobileNumber\" pla" +
                        "ceholder=\"\">\r\n                                </div>\r\n                          " +
                        "  </div>\r\n                            <div class=\"col-md-4 mb-2\">\r\n             " +
                        "                   <div class=\"form-group\">\r\n                                   " +
                        " <label for=\"Email\">Email</label>\r\n                                    <input ty" +
                        "pe=\"text\" class=\"form-control\" id=\"txtEmail\" placeholder=\"\">\r\n                  " +
                        "              </div>\r\n                            </div>\r\n                      " +
                        "      <div class=\"col-md-4 mb-2\">\r\n                                <div class=\"f" +
                        "orm-group\">\r\n                                    <label for=\"VAT/CUI\">VAT/CUI <e" +
                        "m>*</em></label>\r\n                                    <input type=\"text\" class=\"" +
                        "form-control\" id=\"txtVAT\" />\r\n                                </div>\r\n\r\n        " +
                        "                    </div>\r\n                        </div>\r\n\r\n                  " +
                        "      <div class=\"row\">\r\n                            <div class=\"col-md-4 mb-2\">" +
                        "\r\n                                <div class=\"form-group\">\r\n                    " +
                        "                <label for=\"VAT/CUI\">Registration Number</label>\r\n              " +
                        "                      <input type=\"text\" class=\"form-control\" id=\"txtRegisterNum" +
                        "ber\" />\r\n                                </div>\r\n                            </d" +
                        "iv>\r\n                            <div class=\"col-md-4 mb-2\">\r\n                  " +
                        "              <div class=\"form-group\">\r\n                                    <lab" +
                        "el for=\"DueDate\">Due Date in days (For Invoice)</label>\r\n                       " +
                        "             <input type=\"text\" class=\"form-control\" id=\"txtDueDays\" />\r\n       " +
                        "                         </div>\r\n                            </div>\r\n           " +
                        "             </div>\r\n\r\n                        <br />\r\n                        <" +
                        "br />\r\n                        <div class=\"row panel-roles\">\r\n                  " +
                        "          <div class=\"col\">\r\n                                <div class=\"card mb" +
                        "-3\">\r\n                                    <div class=\"card-header\">\r\n           " +
                        "                             <h6 class=\"m-0\">Client - Contact Details\r\n         " +
                        "                              \r\n                                        </h6>\r\n " +
                        "                                   </div>\r\n\r\n                                   " +
                        " <div class=\"card-body\">\r\n                                        <div class=\"ro" +
                        "w filesetcontainer\">\r\n                                            <div class=\"co" +
                        "l-md-12 mb-4\">\r\n                                                <div class=\"lege" +
                        "nd-contactcontainer\">\r\n                                                    <span" +
                        " class=\"addlegend\">\r\n                                                        <bu" +
                        "tton type=\"button\" class=\"btn btn-primary addContact\"><i class=\"fa fa-plus-circl" +
                        "e\" aria-hidden=\"true\"></i>&nbsp;&nbsp;Add Contact</button><span class=\"deletecon" +
                        "tainer\"></span></span>\r\n                                                    <div" +
                        " class=\"headHTML\">\r\n                                                        <div" +
                        " class=\"row align-items-center\">\r\n                                              " +
                        "              <div class=\"col-md-4 mb-2\"><strong>Name</strong> <em>*</em></div>\r" +
                        "\n                                                            <div class=\"col-md-" +
                        "3 mb-2\"><strong>Email</strong> <em>*</em></div>\r\n                               " +
                        "                             <div class=\"col-md-2 mb-2\"><strong>Phone</strong> <" +
                        "em>*</em></div>\r\n                                                            <di" +
                        "v class=\"col-md-2 mb-2\"><strong>Role</strong> <em>*</em></div>\r\n                " +
                        "                                            <div class=\"col-md-1 mb-2\"></div>\r\n " +
                        "                                                       </div>\r\n                 " +
                        "                                   </div>\r\n                                     " +
                        "               <div class=\"row align-items-center row-contact\">\r\n               " +
                        "                                         <div class=\"col-md-4 pr-0\">\r\n          " +
                        "                                                  <input type=\"text\" class=\"form" +
                        "-control txtName\" placeholder=\"Mandatory Info- Contact Name\" />\r\n               " +
                        "                                             \r\n                                 " +
                        "                       </div>\r\n                                                 " +
                        "       <div class=\"col-md-3 pr-0\">\r\n                                            " +
                        "                <input type=\"text\" class=\"form-control txtEmail\" placeholder=\"Ma" +
                        "ndatory Info- Contact Email\" />\r\n                                               " +
                        "         </div>\r\n                                                        <div cl" +
                        "ass=\"col-md-2 pr-0\">\r\n                                                          " +
                        "  <input type=\"text\" class=\"form-control txtPhone\" placeholder=\"Mandatory Info- " +
                        "Phone Number\" />\r\n                                                        </div>" +
                        "\r\n                                                        <div class=\"col-md-2 m" +
                        "b-2\">\r\n                                                            <select class" +
                        "=\"form-control drpItemRole\" id=\"drpItemRole\">\r\n                                 " +
                        "                               <option value=\"Select Role\">Select Role</option>\r" +
                        "\n                                                            </select>\r\n        " +
                        "                                                </div>\r\n                        " +
                        "                                <span class=\"col-md-1 delete\"><i class=\"fa fa-tr" +
                        "ash-o delete-contact\" aria-hidden=\"true\"></i></span>\r\n                          " +
                        "                          </div>\r\n                                              " +
                        "  </div>\r\n                                            </div>\r\n                  " +
                        "                      </div>\r\n                                    </div>\r\n      " +
                        "                          </div>\r\n                            </div>\r\n          " +
                        "              </div>\r\n                        <br />\r\n                        <b" +
                        "r />\r\n                        <div class=\"row panel-roles\">\r\n                   " +
                        "         <div class=\"col\">\r\n                                <div class=\"card mb-" +
                        "3\">\r\n                                    <div class=\"card-header\">\r\n            " +
                        "                            <h6 class=\"m-0\">Client - Bank Account Details\r\n     " +
                        "                                  \r\n                                        </h6" +
                        ">\r\n                                    </div>\r\n\r\n                               " +
                        "     <div class=\"card-body\">\r\n                                        <div class" +
                        "=\"row filesetcontainer\">\r\n                                            <div class" +
                        "=\"col-md-12 mb-4\">\r\n                                                <div class=\"" +
                        "legend-accountcontainer\">\r\n                                                    <" +
                        "span class=\"addlegend\">\r\n                                                       " +
                        " <button type=\"button\" class=\"btn btn-primary addAccount\"><i class=\"fa fa-plus-c" +
                        "ircle\" aria-hidden=\"true\"></i>&nbsp;&nbsp;Add Account</button><span class=\"delet" +
                        "econtainer\"></span></span>\r\n                                                    " +
                        "<div class=\"headHTML\">\r\n                                                        " +
                        "<div class=\"row align-items-center\">\r\n                                          " +
                        "                  <div class=\"col-md-3 mb-2\"><strong>Name Of the Bank</strong> <" +
                        "em>*</em> </div>\r\n                                                            <d" +
                        "iv class=\"col-md-3 mb-2\"><strong>Account Number</strong> <em>*</em></div>\r\n     " +
                        "                                                       <div class=\"col-md-2 mb-2" +
                        "\"><strong>Currency</strong> <em>*</em></div>\r\n                                  " +
                        "                          <div class=\"col-md-3 mb-2\"><strong>Bank Address</stron" +
                        "g> <em>*</em></div>\r\n                                                           " +
                        " <div class=\"col-md-1 mb-2\"></div>\r\n                                            " +
                        "            </div>\r\n                                                    </div>\r\n" +
                        "                                                    <div class=\"row align-items-" +
                        "start row-account\">\r\n                                                        <di" +
                        "v class=\"col-md-3 pr-0\">\r\n                                                      " +
                        "      <input type=\"text\" class=\"form-control txtBankName\" placeholder=\"Mandatory" +
                        " Info - Bank Name\" />\r\n                                                        <" +
                        "/div>\r\n                                                        <div class=\"col-m" +
                        "d-3 pr-0\">\r\n                                                            <input t" +
                        "ype=\"text\" class=\"form-control txtAccount\" placeholder=\"Mandatory Info - Account" +
                        " Number\" />\r\n                                                        </div>\r\n   " +
                        "                                                     <div class=\"col-md-2 mb-2\">" +
                        "\r\n                                                            <select class=\"for" +
                        "m-control drpItemCurrency\" id=\"drpItemCurrency\">\r\n                              " +
                        "                                  <option value=\"Select Currency\">Select Currenc" +
                        "y</option>\r\n                                                            </select" +
                        ">\r\n                                                        </div>\r\n             " +
                        "                                           <div class=\"col-md-3 pr-0\">\r\n        " +
                        "                                                    <textarea placeholder=\"Manda" +
                        "tory Info- Bank Address\" id=\"txtAddress\" class=\"form-control txtAddress\"></texta" +
                        "rea>\r\n                                                        </div>\r\n\r\n        " +
                        "                                                <span class=\"col-md-1 delete\"><i" +
                        " class=\"fa fa-trash-o delete-account\" aria-hidden=\"true\"></i></span>\r\n          " +
                        "                                          </div>\r\n                              " +
                        "                  </div>\r\n                                            </div>\r\n  " +
                        "                                      </div>\r\n                                  " +
                        "  </div>\r\n                                </div>\r\n                            </" +
                        "div>\r\n                        </div>\r\n\r\n\r\n                        <div class=\"ro" +
                        "w\">\r\n                            <div class=\"col mb-2\">\r\n                       " +
                        "         <div class=\"form-group text-right\">\r\n                                  " +
                        "  <button type=\"button\" id=\"btnSave\" class=\"sm-btn btn-outline-primary  mr-3\" va" +
                        "lue=\"Save\">Save</button>\r\n                                    <button type=\"butt" +
                        "on\" id=\"btnCancel\" class=\"sm-btn btn-outline-primary\" value=\"Cancel\">Cancel</but" +
                        "ton>\r\n                                </div>\r\n                            </div>" +
                        "\r\n                        </div>\r\n                    </div>\r\n\r\n                " +
                        "    <div class=\"Bnk-Acc-Info\">\r\n                    </div>\r\n\r\n                </" +
                        "div>\r\n\r\n                <!--Add Customer Ends-->\r\n                <div class=\"ro" +
                        "w tab_Results\" id=\"tab_Employees\">\r\n                    <div class=\"col loaderCo" +
                        "ntent1\">\r\n                        <ul class=\"nav nav-tabs\" id=\"employeetab\" role" +
                        "=\"tablist\">\r\n                            <li class=\"nav-item col pl-0 pr-0\">\r\n  " +
                        "                              <a class=\"nav-link emp_ViewAll active\" id=\"tab-all" +
                        "-clients\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\" aria-controls=\"profile\" a" +
                        "ria-selected=\"false\">All Clients</a>\r\n                            </li>\r\n       " +
                        "                     <li class=\"nav-item col pl-0 pr-0\">\r\n                      " +
                        "          <a class=\"nav-link emp_Active\" id=\"tab-active-clients\" data-toggle=\"ta" +
                        "b\" href=\"#home\" role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">Active Clie" +
                        "nts</a>\r\n                            </li>\r\n                            <li clas" +
                        "s=\"nav-item col pl-0 pr-0\">\r\n                                <a class=\"nav-link " +
                        "emp_InActive\" id=\"tab-inactive-clients\" data-toggle=\"tab\" href=\"#profile\" role=\"" +
                        "tab\" aria-controls=\"profile\" aria-selected=\"false\">Inactive Clients</a>\r\n       " +
                        "                     </li>\r\n\r\n\r\n                        </ul>\r\n                 " +
                        "       <div class=\"preloader1\"><span class=\"preloader-content\" id=\"preloader-Cli" +
                        "ents\">Loading All Clients...</span></div>\r\n                        <div class=\"t" +
                        "ab-content p-3\" id=\"myTabContent\">\r\n                            <div class=\"tab-" +
                        "pane fade show active\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n  " +
                        "                              \r\n                                <div id=\"results" +
                        "Grid\"></div>\r\n                            </div>\r\n                        </div>" +
                        "\r\n                    </div>\r\n                </div>\r\n            </div>\r\n      " +
                        "  </div>\r\n    </div>\r\n\r\n</section>\r\n\r\n\r\n    <script type=\"text/javascript\" src=\"" +
                        "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></scr" +
                        "ipt>\r\n    <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/" +
                        "libs/moment.js/2.22.2/moment.min.js\"></script>\r\n    <script type=\"text/javascrip" +
                        "t\" src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></s" +
                        "cript>\r\n    <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/aja" +
                        "x/libs/tempusdominus-bootstrap-4/5.0.0/js/tempusdominus-bootstrap-4.min.js\"></sc" +
                        "ript>\r\n    <script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/date" +
                        "rangepicker/daterangepicker.min.js\"></script>\r\n\r\n    <!-- Datatable JS -->\r\n\r\n  " +
                        "  <script type=\"text/x-kendo-template\" id=\"selectTemplate_ViewMore\">\r\n    <a cla" +
                        "ss=\"view-more item-viewmore\" onclick=\"openpopup(this)\"><i class=\"fa fa-external-" +
                        "link\" aria-hidden=\"true\"></i><span>View More</span></a>\r\n    </script>\r\n\r\n\r\n\r\n  " +
                        "  <script type=\"text/x-kendo-template\" id=\"selectTemplate_InActive\">\r\n  \r\n      " +
                        "   <div class=\"dropdown settings-icon\" data-id=\"#=data.id#\">                    " +
                        "                                                                                " +
                        "                                                             \r\n     <i data-togg" +
                        "le=\"dropdown\" aria-expanded=\"false\" class=\"fa fa-cogs\" aria-hidden=\"true\"></i>  " +
                        "                                                                                " +
                        "                     \r\n     <div class=\"dropdown-menu dropdown-menu-right\">\r\n   " +
                        "         <a class=\"dropdown-item item-edit d-flex align-items-center\" onclick=\'E" +
                        "ditListItem(this)\'><span class=\"setting-dropdown\"><i class=\"fa fa-pencil-square-" +
                        "o\" aria-hidden=\"true\"></i></span><span>Edit</span></a> \r\n            <a class=\"d" +
                        "ropdown-item d-flex align-items-center\" onclick=\'SendInvitation(this)\'><span cla" +
                        "ss=\"setting-dropdown\"><i class=\"fa fa-paper-plane-o\" aria-hidden=\"true\"></i></sp" +
                        "an><span>Send Invitation</span></a>     \r\n            <a class=\"dropdown-item it" +
                        "em-inactive d-flex align-items-center\" onclick=\'UpdateItemToInActive(this)\'><spa" +
                        "n class=\"setting-dropdown\"><i class=\"fa fa-eye-slash\" aria-hidden=\"true\"></i></s" +
                        "pan><span>Make Inactive</span></a>           \r\n            <a class=\"dropdown-it" +
                        "em item-delete d-flex align-items-center\" onclick=\'DeleteListItem(this)\'><span c" +
                        "lass=\"setting-dropdown\"><i class=\"fa fa-trash-o\" aria-hidden=\"true\"></i></span><" +
                        "span>Delete</span></a>                    \r\n         \r\n                         " +
                        "   \r\n     </div>                                                                " +
                        "                                                                                " +
                        "                                           \r\n </div>\r\n    </script>\r\n    <script" +
                        " type=\"text/x-kendo-template\" id=\"selectTemplate_Active\">\r\n  \r\n         <div cla" +
                        "ss=\"dropdown settings-icon\" data-id=\"#=data.id#\">                               " +
                        "                                                                                " +
                        "                                                  \r\n     <i data-toggle=\"dropdow" +
                        "n\" aria-expanded=\"false\" class=\"fa fa-cogs\" aria-hidden=\"true\"></i>             " +
                        "                                                                                " +
                        "          \r\n     <div class=\"dropdown-menu dropdown-menu-right\">\r\n            <a" +
                        " class=\"dropdown-item item-edit d-flex align-items-center\" onclick=\'EditListItem" +
                        "(this)\'><span class=\"setting-dropdown\"><i class=\"fa fa-pencil-square-o\" aria-hid" +
                        "den=\"true\"></i></span><span>Edit</span></a> \r\n            <a class=\"dropdown-ite" +
                        "m d-flex align-items-center\" onclick=\'SendInvitation(this)\'><span class=\"setting" +
                        "-dropdown\"><i class=\"fa fa-paper-plane-o\" aria-hidden=\"true\"></i></span><span>Se" +
                        "nd Invitation</span></a>     \r\n            <a class=\"dropdown-item item-active d" +
                        "-flex align-items-center\" onclick=\'UpdateItemToActive(this)\'><span class=\"settin" +
                        "g-dropdown\"><i class=\"fa fa-eye-slash\" aria-hidden=\"true\"></i></span><span>Make " +
                        "Active</span></a>           \r\n            <a class=\"dropdown-item item-delete d-" +
                        "flex align-items-center\" onclick=\'DeleteListItem(this)\'><span class=\"setting-dro" +
                        "pdown\"><i class=\"fa fa-trash-o\" aria-hidden=\"true\"></i></span><span>Delete</span" +
                        "></a>                    \r\n         \r\n                            \r\n     </div> " +
                        "                                                                                " +
                        "                                                                                " +
                        "                          \r\n </div>\r\n    </script>\r\n\r\n    <!-- Custom JS -->    " +
                        "   \r\n    <script type=\"text/javascript\" src=\"../../../_layouts/15/TimesheetDemo/" +
                        "/Scripts/Controller/Control_Kendo.js\"></script>\r\n    <script type=\"text/javascri" +
                        "pt\" src=\"../../../_layouts/15/TimesheetDemo/Designs/toastr/toastr.js\"></script>\r" +
                        "\n    <script type=\"text/javascript\" src=\"../../../_layouts/15/TimesheetDemo//Scr" +
                        "ipts/main.js\"></script>\r\n    <script type=\"text/javascript\" src=\"../../../_layou" +
                        "ts/15/TimesheetDemo//Scripts/kendo/kendo.all.min.js\"></script>\r\n    \r\n\r\n    <scr" +
                        "ipt type=\"text/javascript\">\r\n        $(document).ready(function () {\r\n          " +
                        "  $(\'#addemployee\').click(function () {\r\n                $(\'#tab_Employees\').hid" +
                        "e();\r\n            });\r\n\r\n        });\r\n\r\n    </script>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
